### ISSUE TITLE
ActivityManager menu doesn't work

### ISSUE THREAD

**Issue by paiext** [pureqml/pureqml-web#9]
Reproduction steps:
1. go to Docs page
2. click the 'ActivityManger' menu

Error Message:
on data changed callback failed:  SyntaxError: Unexpected token 	 in JSON at position 98
    at JSON.parse (<anonymous>)
    at S.Resource.<anonymous> (qml.index.min.js:1)
    at qml.index.min.js:1
    at qml.index.min.js:1
    at Array.forEach (<anonymous>)
    at l.o.callOnChanged (qml.index.min.js:1)
    at l.o.set (qml.index.min.js:1)
    at S.Resource.Object.defineProperty.set [as data] (qml.index.min.js:1)
    at XMLHttpRequest.done (qml.index.min.js:1) SyntaxError: Unexpected token 	 in JSON at position 98
    at JSON.parse (<anonymous>)
    at S.Resource.<anonymous> (https://pureqml.com/qml.index.min.js:1:63314)
    at https://pureqml.com/qml.index.min.js:1:6966
    at https://pureqml.com/qml.index.min.js:1:6992
    at Array.forEach (<anonymous>)
    at l.o.callOnChanged (https://pureqml.com/qml.index.min.js:1:11583)
    at l.o.set (https://pureqml.com/qml.index.min.js:1:11338)
    at S.Resource.Object.defineProperty.set [as data] (https://pureqml.com/qml.index.min.js:1:13332)
    at XMLHttpRequest.done (https://pureqml.com/qml.index.min.js:1:160534)

**Comment by whoozle** [comment]
fixed docs

but I see problems with ActivityManager example as well: 

event/signal clicked handler failed: TypeError: this.manager.push is not a function
    at Y.MainActivity.P.push (qml.index.min.js:1)
    at O.WebItem.<anonymous> (qml.index.min.js:1)
    at qml.index.min.js:1
    at qml.index.min.js:1
    at Array.forEach (<anonymous>)
    at O.WebItem.l.emitWithArgs (qml.index.min.js:1)
    at O.HoverClickMixin.<anonymous> (qml.index.min.js:1)
    at qml.index.min.js:1
    at qml.index.min.js:1
    at Array.forEach (<anonymous>) TypeError: this.manager.push is not a function
    at Y.MainActivity.P.push (https://pureqml.com/qml.index.min.js:1:34963)
    at O.WebItem.<anonymous> (https://pureqml.com/qml.index.min.js:1:37943)
    at https://pureqml.com/qml.index.min.js:1:6959
    at https://pureqml.com/qml.index.min.js:1:6985
    at Array.forEach (<anonymous>)
    at O.WebItem.l.emitWithArgs (https://pureqml.com/qml.index.min.js:1:16195)
    at O.HoverClickMixin.<anonymous> (https://pureqml.com/qml.index.min.js:1:13719)
    at https://pureqml.com/qml.index.min.js:1:6959
    at https://pureqml.com/qml.index.min.js:1:6985
    at Array.forEach (<anonymous>)

**Comment by comrat** [comment]
We decide to hide activities samples displaying to prevent such confusing
